ampru_joint_publisher:
    type                      : "joint_state_controller/JointStateController"
    publish_rate              : 50

ampru_velocity_controller:
    type                      : "diff_drive_controller/DiffDriveController"
    publish_rate              : 50
    left_wheel                : 'front_left_wheel_joint'
    right_wheel               : 'front_right_wheel_joint'
    pose_covariance_diagonal  : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

# Velocity commands timeout
cmd_vel_timeout: 0.25

# Base frame_id
base_frame_id: base_link

# Odometry fused with IMU is published by robot_localization, so
# no need to publish a TF based on encoders alone.
enable_odom_tf: false

# Velocity and acceleration limits
linear:
    x:
        has_velocity_limits     : true
        max_velocity            : 2.0  # m/s
        has_acceleration_limits : true
        max_acceleration        : 20.0 # m/s^2
angular:
    z:
        has_velocity_limits     : true
        max_velocity            : 4.0  # rad/s
        has_acceleration_limits : true
        max_acceleration        : 25.0 # rad/s^2
        