topics:
-
  name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
-
  name    : remote
  topic   : virtual_joystick/cmd_vel
  timeout : 0.5
  priority: 5
-
  name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1
